name: Python Script Workflow

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 5 * * *'  # Runs at 6 AM (CET) Sweden's Timezone
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_python_script:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  

    - name: Run Python script
      env:
          HYPIXEL_API_KEY: ${{ secrets.HYPIXEL_API_KEY }}
      run: |
        python guild_event.py  # Run your Python script

    - name: Commit CSV file to repository
      env:
        GH_PAT_GUILDEVENTS: ${{ secrets.GH_PAT_GUILDEVENTS }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add csv_files/*  # Add all CSV files in the csv_files folder
        git commit -m "Add generated CSV files"
        git push https://x-access-token:${{ secrets.GH_PAT_GUILDEVENTS }}@github.com/Knattekalle/Skyblock_Guild_Events.git main


